name: Build and Attach Example App to Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.x"

      - name: Build
        run: dotnet build src/GithubActionsPractice/ExampleConsoleApp/ExampleConsoleApp.csproj -c Release -o ./artifacts

      - uses: vimtor/action-zip@v1.1
        with:
          files: ./artifacts/*
          dest: ./artifacts/ExampleConsoleApp.zip

      - name: Upload build to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/ExampleConsoleApp.zip