name: Publish NuGet Package

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  publish:
    name: Publish NuGet Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.x"

      - name: Build Project
        run: dotnet build ./src/GithubActionsPractice/ExampleClassLibrary/ExampleClassLibrary.csproj --configuration Release

      - name: Build NuGet Package
        run: dotnet pack ./src/GithubActionsPractice/ExampleClassLibrary/ExampleClassLibrary.csproj --configuration Release --no-build --output ./artifacts

      - name: Publish NuGet Package to GitHub registry
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --no-symbols
        env:
          GH_PAT: ${{ secrets.NUGET_API_KEY }}
