name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'  # Adjust the .NET SDK version

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build and Publish NuGet Package
      run: dotnet pack -c Release --output ./artifacts
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Publish NuGet Package
      run: dotnet nuget push ./artifacts/*.nupkg --source https://nuget.pkg.github.com/gnalvesteffer/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
