name: Publish NuGet Package

on:
  push:
    branches:
      - main
    paths:
      - src/GithubActionsPractice/ExampleClassLibrary/**
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.x"

      - name: Build Project & Package
        run: dotnet build src/GithubActionsPractice/ExampleClassLibrary/ExampleClassLibrary.csproj --configuration Release --output ./artifacts

      - name: Publish NuGet Package to GitHub registry
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ github.token }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --no-symbols

      - name: Upload package to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*.nupkg
