name: Publish NuGet Package

on:
  push:
    branches:
      - main
    paths:
      - ./src/GithubActionsPractice/ExampleClassLibrary/**
  release:
    types: [published]

jobs:
  build:
    name: Build ExampleClassLibrary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: Build Project
        run: dotnet build ./src/GithubActionsPractice/ExampleClassLibrary/ExampleClassLibrary.csproj --configuration Release

  publish:
    needs: build
    name: Publish ExampleClassLibrary NuGet Package
    runs-on: ubuntu-latest
    steps:
      - name: Build NuGet Package
        run: dotnet pack ./src/GithubActionsPractice/ExampleClassLibrary/ExampleClassLibrary.csproj --configuration Release --no-build --output ./artifacts

      - name: Publish NuGet Package to GitHub registry
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --no-symbols
