name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'

    - name: Build Project
      run: dotnet build ./src/GithubActionsPractice/ExampleClassLibrary/ExampleClassLibrary.csproj --configuration Release 

    - name: Build Nuget Package
      run: dotnet pack ./src/GithubActionsPractice/ExampleClassLibrary/ExampleClassLibrary.csproj --configuration Release --no-build --output .

    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push ./src/GithubActionsPractice/ExampleClassLibrary/bin/Release/gnalvesteffer_nugetpractice.0.0.0.nupkg --api-key ${GH_PAT} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate --no-symbols 
      env:
        GH_PAT: ${{ secrets.GH_PAT }}